---
namespace: rarango9
name: macmods
version: 0.0.7
readme: README.md
authors:
  - Rob Arango
description: Collection of MacOS related roles to automate system configuration.
license_file: "LICENSE"

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: []

dependencies:
  community.general: ">=4.0.1"

repository: https://github.com/rarango9/ansible-collection-macmods
documentation: https://github.com/rarango9/ansible-collection-macmods/README.md
issues: https://github.com/rarango9/ansible-collection-macmods/issues

build_ignore: [
  ".editorconfig",
  "requriements.txt"
]
