---
- name: Remove dock items
  ansible.builtin.command:
    cmd: dockutil --remove '{{ item }}' --no-restart
  register: item_removed
  changed_when: "'was not found' not in item_removed.stdout"
  loop: "{{ dock_remove_items }}"
  notify:
    - Restart dock

- name: Add dock items
  ansible.builtin.command:
    cmd: dockutil --add '{{ item.path }}' --no-restart
  register: item_added
  changed_when: "'already exists in dock' not in item_added.stdout"
  failed_when: no
  loop: "{{ dock_persist_items }}"
  notify:
    - Restart dock

- name: Position dock items
  ansible.builtin.command:
    cmd: dockutil --move "{{ item.label }}" --position "{{ item.pos }}" --no-restart
  loop: "{{ dock_persist_items | sort(attribute='pos') }}"
  when:
    - item.pos is defined
    - item.pos > 0
    - lookup("pipe", "dockutil --find '" + item.label + "' | sed -r 's/.*slot (.*) in.*/\\1/g'") | int != item.pos
  notify:
    - Restart dock
