---
- name: Remove existing Command Line Tools, be patient
  ansible.builtin.file:
    path: /Library/Developer/CommandLineTools
    state: absent
  when: command_line_tools_force_install
  become: yes

- name: Check if Command Line Tools are installed
  ansible.builtin.stat:
    path: /Library/Developer/CommandLineTools/usr/bin/git
  register: clt_installed
  changed_when: not clt_installed.stat.exists

- import_tasks: install.yml
  when: not clt_installed.stat.exists
