---
- name: Ensure homebrew parent directory exists with permissions
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    mode: "{{ '0775' if ansible_distribution_version is version('10.13', '<') else omit }}"
    owner: "{{ (ansible_machine == 'arm64') | ternary(ansible_user_id, 'root') }}"
    group: "{{ 'admin' if ansible_distribution_version is version('10.13', '<') else omit }}"
  become: yes

- name: Ensure homebrew_respository directory exists with permissions
  ansible.builtin.file:
    path: "{{ homebrew_repository }}"
    state: directory
    mode: 0775
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  become: yes

- name: Ensure homebrew is installed
  ansible.builtin.git:
    repo: "{{ homebrew_repo_url }}"
    version: master
    dest: "{{ homebrew_repository }}"
    update: false
    depth: 1
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Ensure proper permissions and ownership on homebrew bin directory
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}/bin"
    state: directory
    mode: 0775
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  become: yes

- name: Ensure proper ownership on homebrew_repository subdirectories
  ansible.builtin.file:
    path: "{{ homebrew_repository }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    recurse: yes
  become: yes

- name: Symlink brew binary to homebrew bin directory
  ansible.builtin.file:
    src: "{{ homebrew_repository }}/bin/brew"
    dest: "{{ homebrew_prefix }}/bin/brew"
    state: link
  become: yes

- name: Ensure homebrew directories are in place
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  become: yes
  loop: "{{ homebrew_directories }}"

- name: Always force update homebrew
  ansible.builtin.command:
    cmd: "{{ homebrew_prefix }}/bin/brew update --force"
  register: homebrew_force_update
  changed_when: "'Already up-to-date.' not in homebrew_force_update.stderr"
