---
# Parent directory that Homebrew will be installed to.
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"

# Homebrews installation directory, in this case the cloned repository.
homebrew_repository: "{{ homebrew_prefix }}/Homebrew"

# Remove any repositories that are tapped.
homebrew_taps_remove: []
# - hashicorp/tap

# By default homebrew/core is tapped, add any other repositories to tap here.
homebrew_taps_install: []
# - name: hashicorp/tap
#   url: https://github.com/hashicorp/homebrew-tap
# - hashicorp/tap

# List of Homebrew packages to remove.
homebrew_packages_remove: []
# - groovy

# List of Homebrew packages to install.
homebrew_packages_install: []
# - git
# - name: git
#   state: latest

# Should all defined Homebrew packages be upgraded to latest versions.
homebrew_packages_upgrade_all: no

# List of Homebrew cask apps to remove.
homebrew_casks_remove: []
# - alfred
# - wireshark

# List of Homebrew cask apps to install.
homebrew_casks_install: []
# - google-chrome
# - name: google-chrome
#   state: latest
#   greedy: yes

# Should all defined Homebrew cask apps be upgraded.
homebrew_casks_upgrade_all: no
