---
# URL to the Homebrew/brew repository.
homebrew_repo_url: https://github.com/Homebrew/brew

# Homebrew subdirectories list.
homebrew_directories:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var
